#!/usr/bin/env node
/*
 * sync_orcid.mjs — regenerate the full bibliography from Anna's public ORCID record.
 *
 * WHY: the featured papers in src/data/publications.ts carry hand-written
 * plain-language summaries — that's the HUMAN layer and this script never touches
 * it. This script only refreshes the MACHINE layer: the complete list of works.
 * Keeping them separate means an automated sync can never clobber Anna's prose.
 *
 * Uses the ORCID *public* API — no key, no token, no secret required.
 *
 *   node scripts/publications/sync_orcid.mjs            # write the JSON
 *   node scripts/publications/sync_orcid.mjs --check    # exit 1 if out of date (CI)
 *
 * Output: src/data/generated/publications.json (generated — do not hand-edit)
 */

import { writeFileSync, readFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ORCID = process.env.ORCID_ID ?? "0000-0003-4423-0660";
const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../../src/data/generated/publications.json");

/** Normalized title used only for de-duplicating preprint vs published versions. */
const key = (t) => (t ?? "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

/** Pull an arXiv id out of an ORCID external id (bibcode or the arXiv DOI form). */
function arxivId(ids) {
  const direct = ids.find((i) => i.type === "arxiv")?.value;
  if (direct) return direct.replace(/^arxiv:/i, "");
  const doi = ids.find((i) => i.type === "doi")?.value ?? "";
  const m = doi.match(/10\.48550\/arxiv\.(.+)$/i);
  return m ? m[1] : null;
}

async function fetchWorks() {
  const res = await fetch(`https://pub.orcid.org/v3.0/${ORCID}/works`, {
    headers: { Accept: "application/json" },
  });
  if (!res.ok) throw new Error(`ORCID ${res.status} ${res.statusText}`);
  const data = await res.json();

  const records = [];
  for (const group of data.group ?? []) {
    const s = group["work-summary"]?.[0];
    if (!s) continue;
    const ids = (s["external-ids"]?.["external-id"] ?? []).map((x) => ({
      type: (x["external-id-type"] ?? "").toLowerCase(),
      value: x["external-id-value"] ?? "",
    }));
    records.push({
      title: s.title?.title?.value ?? null,
      year: s["publication-date"]?.year?.value ?? null,
      venue: s["journal-title"]?.value ?? null,
      type: s.type ?? null,
      doi: ids.find((i) => i.type === "doi")?.value ?? null,
      bibcode: ids.find((i) => i.type === "bibcode")?.value ?? null,
      arxiv: arxivId(ids),
    });
  }
  return records.filter((r) => r.title);
}

/**
 * Collapse preprint + published versions of the same paper into one record,
 * preferring the journal version but keeping the arXiv id and earliest year info.
 */
function dedupe(records) {
  const byTitle = new Map();
  for (const r of records) {
    const k = key(r.title);
    const prev = byTitle.get(k);
    if (!prev) { byTitle.set(k, r); continue; }
    const isPreprint = (x) => !x.venue || /arxiv/i.test(x.venue);
    // Keep whichever is the published version; merge the other's arXiv id.
    const [keep, drop] = isPreprint(prev) && !isPreprint(r) ? [r, prev] : [prev, r];
    keep.arxiv = keep.arxiv ?? drop.arxiv;
    keep.bibcode = keep.bibcode ?? drop.bibcode;
    byTitle.set(k, keep);
  }
  return [...byTitle.values()].sort(
    (a, b) => (Number(b.year) || 0) - (Number(a.year) || 0) || a.title.localeCompare(b.title),
  );
}

const works = dedupe(await fetchWorks());
const payload = {
  _comment:
    "GENERATED by scripts/publications/sync_orcid.mjs from the public ORCID record. Do not hand-edit; curated summaries live in src/data/publications.ts.",
  source: `https://orcid.org/${ORCID}`,
  count: works.length,
  works,
};
const json = JSON.stringify(payload, null, 2) + "\n";

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== json) {
    console.error(`[stale] ${OUT} differs from ORCID (${works.length} works).`);
    process.exit(1);
  }
  console.log(`[ok] up to date (${works.length} works)`);
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, json);
  console.log(`[ok] wrote ${works.length} works -> ${OUT}`);
}
