/*
 * check-lupton.mjs — validate the Lupton RGB mapping against ASTROPY ITSELF.
 *
 * This gate is a different kind from the others in this repo. Most of them assert an
 * internal invariant or a published number; this one compares against a REFERENCE
 * IMPLEMENTATION, over 252 cases spanning six (stretch, Q) settings and inputs from
 * zero to 1000, including negatives and per-band minima.
 *
 * That matters because mirroring an algorithm from its source is exactly the task where
 * being 95% right feels identical to being right. The failure mode is a plausible
 * image, not an exception — the same shape of problem as the missing factor of pi in
 * `passbands.ts`, which was invisible for as long as only ratios were compared.
 *
 * Values come from `scripts/reference/lupton-astropy.json`, generated by
 * `scripts/reference/gen-lupton-ref.py` against the installed astropy. The authority is
 * the public repository, not a local checkout — same rule as the filter curves, and for
 * the same reason: a local path is an audit trail nobody else can follow.
 *
 * WHY TRUNCATION-CONSISTENCY RATHER THAN EQUALITY. astropy converts to uint8 with
 * `.astype(np.uint8)`, which truncates. Comparing truncated integers therefore amplifies
 * float noise by fourteen orders of magnitude: one case lands on exactly 102.0 in
 * numpy's operation order and on 101.999999999999986 in JavaScript's, and floor() turns
 * a 1.4e-14 difference into a whole display level. So the assertion is that the float
 * value is consistent with astropy's integer to within 1e-9 — which is a stronger claim
 * about the arithmetic than integer equality, not a weaker one.
 */
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  luptonRGB,
  luptonIntensity,
  luptonStretchedIntensity,
  luptonSlope,
  luptonQ,
  LUPTON_Q,
  luptonIntensityForOutput,
  luptonDepthMag,
  luptonQForDepth,
} from "../src/novascope/core/imaging/lupton.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
let failures = 0;
const ok = (cond, msg) => {
  console.log(`  ${cond ? "ok  " : "FAIL"}  ${msg}`);
  if (!cond) failures++;
};

console.log("lupton (RGB mapping, validated against astropy):");

const ref = JSON.parse(readFileSync(resolve(HERE, "reference/lupton-astropy.json"), "utf8"));
ok(ref.cases.length >= 200, `${ref.cases.length} reference cases from astropy ${ref.astropyVersion}`);
ok(/^https:\/\/github\.com\/astropy/.test(ref.authority), "the authority is astropy's public repository");
ok(/Lupton et al\. \(2004\)/.test(ref.reference), "…and the literature reference is recorded");

/* ── THE CROSS-VALIDATION ── */
{
  const EPS = 1e-9;
  let worst = 0;
  let worstDesc = "";
  let mismatches = 0;
  let exactFloor = 0;
  let channels = 0;
  for (const c of ref.cases) {
    const got = luptonRGB(c.r, c.g, c.b, {
      stretch: c.stretch,
      q: c.Q,
      ...(c.minimum ? { minimum: c.minimum } : {}),
    });
    for (let k = 0; k < 3; k++) {
      channels++;
      const mine = got[k] * 255;
      const want = c.out[k];
      // Truncation-consistent: astropy's floor bracket, widened by float slop only.
      const consistent = mine + EPS >= want && mine - EPS < want + 1;
      if (!consistent) {
        mismatches++;
        const d = Math.abs(mine - want);
        if (d > worst) {
          worst = d;
          worstDesc = `${JSON.stringify(c)} ch${k}: ${mine} vs ${want}`;
        }
      }
      if (Math.floor(mine) === want) exactFloor++;
    }
  }
  ok(mismatches === 0, `all ${channels} channels agree with astropy${mismatches ? ` — worst ${worstDesc}` : ""}`);
  // Reported rather than asserted at 100%: the one exact-integer coincidence is a float
  // ordering artefact, and demanding integer identity would be asserting that V8 and
  // numpy sum three doubles in the same order, which is not a property of this module.
  ok(
    exactFloor >= channels - 2,
    `…and ${exactFloor}/${channels} match even after truncation (at most 2 integer-boundary coincidences)`,
  );
}

/* ── THE PROPERTY THE ALGORITHM EXISTS FOR ──
 *
 * Hue must survive both the stretch and the clip. This is the whole reason to use Lupton
 * rather than stretching each channel independently, and it is what stops a saturated
 * star from washing out to white. Asserted on RATIOS, since that is what hue is. */
{
  const hue = ([r, g, b]) => {
    const s = r + g + b;
    return s > 0 ? [r / s, g / s, b / s] : [0, 0, 0];
  };
  const base = [5, 2, 0.5];
  const ratios = [];
  for (const k of [0.01, 0.1, 1, 10, 100, 1000, 1e5]) {
    ratios.push(hue(luptonRGB(base[0] * k, base[1] * k, base[2] * k)));
  }
  // Below saturation the hue is exactly the input's; above it, the common-mode clamp
  // keeps it so. Either way it must not drift toward grey as intensity rises.
  const first = ratios[0];
  const drift = Math.max(...ratios.map((r) => Math.max(...r.map((v, i) => Math.abs(v - first[i])))));
  ok(drift < 1e-9, `hue is invariant over 7 decades of intensity (drift ${drift.toExponential(1)})`);

  // The concrete statement: a saturated star keeps its colour.
  const sat = luptonRGB(1e6, 4e5, 1e5);
  ok(Math.max(...sat) > 0.999, "a very bright star does saturate its brightest channel");
  ok(sat[2] < 0.3, `…but stays coloured rather than white (blue channel ${sat[2].toFixed(3)})`);
  const grey = luptonRGB(1e6, 1e6, 1e6);
  ok(Math.min(...grey) > 0.999, "…while a genuinely neutral source does go white");
}

/* ── Monotonicity and boundaries ── */
{
  let prev = -1;
  let mono = true;
  for (let i = 0; i < 200; i++) {
    const v = luptonIntensity(...luptonRGB(10 ** (i / 20 - 5), 10 ** (i / 20 - 5), 10 ** (i / 20 - 5)));
    if (v < prev - 1e-15) mono = false;
    prev = v;
  }
  ok(mono, "output intensity is non-decreasing in input intensity");

  ok(luptonRGB(0, 0, 0).every((v) => v === 0), "zero flux is black, not NaN — the sky between stars");
  ok(luptonRGB(-1, -1, -1).every((v) => v === 0), "negative intensity is black rather than a NaN or a wrap");
  ok(luptonRGB(1, 1, 1).every((v) => Number.isFinite(v)), "unit input is finite");
  ok(
    luptonRGB(1, 0, 0, { minimum: [2, 0, 0] }).every((v) => v >= 0),
    "a per-band minimum above the data cannot produce a negative channel",
  );
  const big = luptonRGB(1e300, 1e299, 1e298);
  ok(big.every(Number.isFinite) && Math.max(...big) <= 1, "an absurd input clamps rather than overflowing");
}

/* ── Astropy's Q sanitization, reproduced so edge cases match rather than diverge ── */
{
  ok(luptonQ(0) === 0.1, "Q = 0 becomes 0.1, as astropy does, instead of dividing by zero");
  ok(luptonQ(1e12) === 1e10, "an enormous Q clamps to 1e10");
  ok(luptonQ(8) === 8, "an ordinary Q passes through");
  ok(Math.abs(luptonSlope(8) - 0.1 / Math.asinh(0.8)) < 1e-15, "the slope is frac / asinh(frac Q) exactly");
  ok(LUPTON_Q === 8, "the default Q is astropy's 8");
  /* Q and stretch are different controls and must not be presented as one.
   *
   * Q PIVOTS about I = frac * stretch rather than simply brightening: the slope
   * normalization anchors every Q to the same value there, so a larger Q lifts faint
   * detail and compresses bright detail at once. My first version of this assertion
   * claimed "a larger Q lifts a faint pixel" and tested it at I = 1 with stretch = 5 —
   * which is ABOVE the anchor at 0.5, where the effect reverses. The code was right and
   * the assertion was wrong, so the pivot itself is what gets gated. */
  const STRETCH = 5;
  const ANCHOR = 0.1 * STRETCH; // frac * stretch
  for (const q of [4, 8, 20, 100]) {
    ok(
      Math.abs(luptonStretchedIntensity(ANCHOR, STRETCH, q) - 0.1) < 1e-12,
      `Q = ${q}: the curve passes through frac at I = frac*stretch (the pivot every Q shares)`,
    );
  }
  const faint = 0.01;
  const bright = 50;
  ok(
    luptonStretchedIntensity(faint, STRETCH, 20) > luptonStretchedIntensity(faint, STRETCH, 8),
    "below the pivot a larger Q lifts faint detail",
  );
  ok(
    luptonStretchedIntensity(bright, STRETCH, 20) < luptonStretchedIntensity(bright, STRETCH, 8),
    "…and above it a larger Q compresses bright detail — a pivot, not a brightener",
  );
  ok(
    luptonStretchedIntensity(1, 20, 8) < luptonStretchedIntensity(1, 5, 8),
    "a larger stretch dims a fixed intensity — genuinely the other control",
  );
}

/* ── THE INVERSE ──
 *
 * `luptonIntensityForOutput` takes over from `limitingFluxRatio` for the Lupton path:
 * it is what sizes a star's billboard to hold exactly the visible part of its PSF, and
 * what turns the display threshold into a depth in magnitudes.
 *
 * It is a CLOSED FORM rather than a bisection, deliberately. `softeningForLimit` is the
 * same shape of function and its first version was inverted, answering a 10-magnitude
 * request with 30.6 magnitudes; a closed form removes that class of bug instead of
 * gating against it. The round trip is still checked, because "closed form" is a claim
 * about the algebra and the algebra can be wrong. */
{
  let worst = 0;
  let worstDesc = "";
  for (const stretch of [0.1, 1, 5, 20, 1000]) {
    for (const q of [0.5, 8, 30, 100]) {
      for (const t of [1 / 255, 0.01, 0.1, 0.5, 1, 2]) {
        const I = luptonIntensityForOutput(t, stretch, q);
        const back = luptonStretchedIntensity(I, stretch, q);
        const err = Math.abs(back - t) / t;
        if (err > worst) {
          worst = err;
          worstDesc = `stretch=${stretch} Q=${q} t=${t}`;
        }
      }
    }
  }
  ok(worst < 1e-12, `output -> intensity -> output round-trips (worst ${worst.toExponential(1)} at ${worstDesc})`);

  // …and the other direction, over the intensities a star field actually spans.
  let worstI = 0;
  for (const stretch of [1, 5, 20]) {
    for (let e = -8; e <= 6; e++) {
      const I = 10 ** e;
      const back = luptonIntensityForOutput(luptonStretchedIntensity(I, stretch), stretch);
      worstI = Math.max(worstI, Math.abs(back - I) / I);
    }
  }
  ok(worstI < 1e-9, `intensity -> output -> intensity round-trips over 14 decades (worst ${worstI.toExponential(1)})`);

  // Direction, which is the thing the analogous bug got wrong.
  ok(
    luptonIntensityForOutput(0.5, 5) > luptonIntensityForOutput(1 / 255, 5),
    "a brighter target needs a higher intensity — the direction softeningForLimit inverted",
  );
  ok(
    luptonIntensityForOutput(1 / 255, 20) > luptonIntensityForOutput(1 / 255, 5),
    "a larger stretch pushes the visibility threshold to higher flux",
  );

  /* The number this exists to produce: how many magnitudes of dynamic range the display
   * curve spans, from one 8-bit level up to white. Reported so it is comparable with the
   * asinh path's 19.8 mag rather than being a different unnameable quantity. */
  for (const stretch of [1, 5, 20]) {
    const faint = luptonIntensityForOutput(1 / 255, stretch);
    const white = luptonIntensityForOutput(1, stretch);
    const depth = -2.5 * Math.log10(faint / white);
    ok(depth > 5 && depth < 40, `stretch ${stretch}: the curve spans ${depth.toFixed(1)} mag from one display level to white`);
  }
}

/* ── DEPTH IN MAGNITUDES, AND ITS INVERSE ──
 *
 * This is what lets the page go on asking for "19.8 magnitudes of depth" while the
 * display transfer changes underneath it. The depth is the physical statement; Q is
 * merely the parameter that delivers it, and nothing outside this module should name Q.
 */
{
  /* ORTHOGONALITY, which is not obvious: `stretch` is a pure scale on intensity, so it
   * moves both ends of the faint/white ratio equally and cancels out of the depth
   * entirely. Q sets how much dynamic range the curve holds; stretch sets which flux
   * sits in the middle of it. A UI that merged them would be merging two different
   * things, so the independence is asserted rather than assumed. */
  for (const q of [1, 8, 30, 200]) {
    const depths = [0.1, 1, 5, 100, 1e4].map((s) => luptonDepthMag(q, s));
    const spread = Math.max(...depths) - Math.min(...depths);
    ok(spread < 1e-9, `Q = ${q}: depth is independent of stretch (spread ${spread.toExponential(1)} mag)`);
  }

  /* MONOTONICITY before the bisection is trusted — same precaution as
   * massForMagnitudeLimit, and for the same reason. */
  {
    let prev = -Infinity;
    let mono = true;
    for (let i = 0; i <= 400; i++) {
      const q = 0.1 * (1e10 / 0.1) ** (i / 400);
      const d = luptonDepthMag(q);
      if (!(d > prev)) mono = false;
      prev = d;
    }
    ok(mono, "depth is strictly increasing in Q over the whole search bracket");
  }

  // The round trip, which is the assertion softeningForLimit needed and did not have.
  let worst = 0;
  let worstAt = 0;
  for (const d of [6.5, 8, 11.06, 15, 19.78, 25, 34, 50]) {
    const back = luptonDepthMag(luptonQForDepth(d));
    if (Math.abs(back - d) > worst) {
      worst = Math.abs(back - d);
      worstAt = d;
    }
  }
  ok(worst < 1e-9, `depth -> Q -> depth round-trips (worst ${worst.toExponential(1)} mag at ${worstAt})`);

  ok(Math.abs(luptonDepthMag(8) - 11.06) < 0.02, `astropy's default Q = 8 is a ${luptonDepthMag(8).toFixed(2)} mag stretch`);
  ok(
    Math.abs(luptonDepthMag(luptonQForDepth(19.78)) - 19.78) < 1e-9,
    `Q = ${luptonQForDepth(19.78).toFixed(2)} reproduces the asinh path's 19.78 mag exactly`,
  );
  ok(luptonQForDepth(19.78) > 8, "…which is deeper than astropy's default, so the images are not directly comparable");
  // Saturating rather than lying, at both ends.
  ok(luptonQForDepth(0) === 0.1, "a non-positive depth request clamps to the shallowest Q");
  ok(luptonQForDepth(1e6) === 1e10, "an absurd depth request clamps rather than diverging");
  ok(Number.isFinite(luptonQForDepth(Number.NaN)) , "a NaN depth returns a finite Q rather than propagating");
}

if (failures) {
  console.error(`\n✗ lupton — ${failures} failure(s)`);
  process.exit(1);
}
console.log("\n✓ lupton ok");
