/*
 * check-lupton.mjs — validate the Lupton RGB mapping against ASTROPY ITSELF.
 *
 * This gate is a different kind from the others in this repo. Most of them assert an
 * internal invariant or a published number; this one compares against a REFERENCE
 * IMPLEMENTATION, over 252 cases spanning six (stretch, Q) settings and inputs from
 * zero to 1000, including negatives and per-band minima.
 *
 * That matters because mirroring an algorithm from its source is exactly the task where
 * being 95% right feels identical to being right. The failure mode is a plausible
 * image, not an exception — the same shape of problem as the missing factor of pi in
 * `passbands.ts`, which was invisible for as long as only ratios were compared.
 *
 * Values come from `scripts/reference/lupton-astropy.json`, generated by
 * `scripts/reference/gen-lupton-ref.py` against the installed astropy. The authority is
 * the public repository, not a local checkout — same rule as the filter curves, and for
 * the same reason: a local path is an audit trail nobody else can follow.
 *
 * WHY TRUNCATION-CONSISTENCY RATHER THAN EQUALITY. astropy converts to uint8 with
 * `.astype(np.uint8)`, which truncates. Comparing truncated integers therefore amplifies
 * float noise by fourteen orders of magnitude: one case lands on exactly 102.0 in
 * numpy's operation order and on 101.999999999999986 in JavaScript's, and floor() turns
 * a 1.4e-14 difference into a whole display level. So the assertion is that the float
 * value is consistent with astropy's integer to within 1e-9 — which is a stronger claim
 * about the arithmetic than integer equality, not a weaker one.
 */
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  luptonRGB,
  luptonIntensity,
  luptonStretchedIntensity,
  luptonSlope,
  luptonQ,
  LUPTON_Q,
} from "../src/novascope/core/imaging/lupton.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
let failures = 0;
const ok = (cond, msg) => {
  console.log(`  ${cond ? "ok  " : "FAIL"}  ${msg}`);
  if (!cond) failures++;
};

console.log("lupton (RGB mapping, validated against astropy):");

const ref = JSON.parse(readFileSync(resolve(HERE, "reference/lupton-astropy.json"), "utf8"));
ok(ref.cases.length >= 200, `${ref.cases.length} reference cases from astropy ${ref.astropyVersion}`);
ok(/^https:\/\/github\.com\/astropy/.test(ref.authority), "the authority is astropy's public repository");
ok(/Lupton et al\. \(2004\)/.test(ref.reference), "…and the literature reference is recorded");

/* ── THE CROSS-VALIDATION ── */
{
  const EPS = 1e-9;
  let worst = 0;
  let worstDesc = "";
  let mismatches = 0;
  let exactFloor = 0;
  let channels = 0;
  for (const c of ref.cases) {
    const got = luptonRGB(c.r, c.g, c.b, {
      stretch: c.stretch,
      q: c.Q,
      ...(c.minimum ? { minimum: c.minimum } : {}),
    });
    for (let k = 0; k < 3; k++) {
      channels++;
      const mine = got[k] * 255;
      const want = c.out[k];
      // Truncation-consistent: astropy's floor bracket, widened by float slop only.
      const consistent = mine + EPS >= want && mine - EPS < want + 1;
      if (!consistent) {
        mismatches++;
        const d = Math.abs(mine - want);
        if (d > worst) {
          worst = d;
          worstDesc = `${JSON.stringify(c)} ch${k}: ${mine} vs ${want}`;
        }
      }
      if (Math.floor(mine) === want) exactFloor++;
    }
  }
  ok(mismatches === 0, `all ${channels} channels agree with astropy${mismatches ? ` — worst ${worstDesc}` : ""}`);
  // Reported rather than asserted at 100%: the one exact-integer coincidence is a float
  // ordering artefact, and demanding integer identity would be asserting that V8 and
  // numpy sum three doubles in the same order, which is not a property of this module.
  ok(
    exactFloor >= channels - 2,
    `…and ${exactFloor}/${channels} match even after truncation (at most 2 integer-boundary coincidences)`,
  );
}

/* ── THE PROPERTY THE ALGORITHM EXISTS FOR ──
 *
 * Hue must survive both the stretch and the clip. This is the whole reason to use Lupton
 * rather than stretching each channel independently, and it is what stops a saturated
 * star from washing out to white. Asserted on RATIOS, since that is what hue is. */
{
  const hue = ([r, g, b]) => {
    const s = r + g + b;
    return s > 0 ? [r / s, g / s, b / s] : [0, 0, 0];
  };
  const base = [5, 2, 0.5];
  const ratios = [];
  for (const k of [0.01, 0.1, 1, 10, 100, 1000, 1e5]) {
    ratios.push(hue(luptonRGB(base[0] * k, base[1] * k, base[2] * k)));
  }
  // Below saturation the hue is exactly the input's; above it, the common-mode clamp
  // keeps it so. Either way it must not drift toward grey as intensity rises.
  const first = ratios[0];
  const drift = Math.max(...ratios.map((r) => Math.max(...r.map((v, i) => Math.abs(v - first[i])))));
  ok(drift < 1e-9, `hue is invariant over 7 decades of intensity (drift ${drift.toExponential(1)})`);

  // The concrete statement: a saturated star keeps its colour.
  const sat = luptonRGB(1e6, 4e5, 1e5);
  ok(Math.max(...sat) > 0.999, "a very bright star does saturate its brightest channel");
  ok(sat[2] < 0.3, `…but stays coloured rather than white (blue channel ${sat[2].toFixed(3)})`);
  const grey = luptonRGB(1e6, 1e6, 1e6);
  ok(Math.min(...grey) > 0.999, "…while a genuinely neutral source does go white");
}

/* ── Monotonicity and boundaries ── */
{
  let prev = -1;
  let mono = true;
  for (let i = 0; i < 200; i++) {
    const v = luptonIntensity(...luptonRGB(10 ** (i / 20 - 5), 10 ** (i / 20 - 5), 10 ** (i / 20 - 5)));
    if (v < prev - 1e-15) mono = false;
    prev = v;
  }
  ok(mono, "output intensity is non-decreasing in input intensity");

  ok(luptonRGB(0, 0, 0).every((v) => v === 0), "zero flux is black, not NaN — the sky between stars");
  ok(luptonRGB(-1, -1, -1).every((v) => v === 0), "negative intensity is black rather than a NaN or a wrap");
  ok(luptonRGB(1, 1, 1).every((v) => Number.isFinite(v)), "unit input is finite");
  ok(
    luptonRGB(1, 0, 0, { minimum: [2, 0, 0] }).every((v) => v >= 0),
    "a per-band minimum above the data cannot produce a negative channel",
  );
  const big = luptonRGB(1e300, 1e299, 1e298);
  ok(big.every(Number.isFinite) && Math.max(...big) <= 1, "an absurd input clamps rather than overflowing");
}

/* ── Astropy's Q sanitization, reproduced so edge cases match rather than diverge ── */
{
  ok(luptonQ(0) === 0.1, "Q = 0 becomes 0.1, as astropy does, instead of dividing by zero");
  ok(luptonQ(1e12) === 1e10, "an enormous Q clamps to 1e10");
  ok(luptonQ(8) === 8, "an ordinary Q passes through");
  ok(Math.abs(luptonSlope(8) - 0.1 / Math.asinh(0.8)) < 1e-15, "the slope is frac / asinh(frac Q) exactly");
  ok(LUPTON_Q === 8, "the default Q is astropy's 8");
  /* Q and stretch are different controls and must not be presented as one.
   *
   * Q PIVOTS about I = frac * stretch rather than simply brightening: the slope
   * normalization anchors every Q to the same value there, so a larger Q lifts faint
   * detail and compresses bright detail at once. My first version of this assertion
   * claimed "a larger Q lifts a faint pixel" and tested it at I = 1 with stretch = 5 —
   * which is ABOVE the anchor at 0.5, where the effect reverses. The code was right and
   * the assertion was wrong, so the pivot itself is what gets gated. */
  const STRETCH = 5;
  const ANCHOR = 0.1 * STRETCH; // frac * stretch
  for (const q of [4, 8, 20, 100]) {
    ok(
      Math.abs(luptonStretchedIntensity(ANCHOR, STRETCH, q) - 0.1) < 1e-12,
      `Q = ${q}: the curve passes through frac at I = frac*stretch (the pivot every Q shares)`,
    );
  }
  const faint = 0.01;
  const bright = 50;
  ok(
    luptonStretchedIntensity(faint, STRETCH, 20) > luptonStretchedIntensity(faint, STRETCH, 8),
    "below the pivot a larger Q lifts faint detail",
  );
  ok(
    luptonStretchedIntensity(bright, STRETCH, 20) < luptonStretchedIntensity(bright, STRETCH, 8),
    "…and above it a larger Q compresses bright detail — a pivot, not a brightener",
  );
  ok(
    luptonStretchedIntensity(1, 20, 8) < luptonStretchedIntensity(1, 5, 8),
    "a larger stretch dims a fixed intensity — genuinely the other control",
  );
}

if (failures) {
  console.error(`\n✗ lupton — ${failures} failure(s)`);
  process.exit(1);
}
console.log("\n✓ lupton ok");
